### ISSUE TITLE
--use_system_libnanomsg=true is broken after the update to 0.9-beta

### ISSUE THREAD

**Issue by deepakprabhakara** [nickdesaulniers/node-nanomsg#157]
Because the pkg-config file include directory is now "/usr/local/include" and not "/usr/local/include/nanomsg" using the flag above causes the build to fail since it can't find <nn.h>

Fix would be most likely in binding.gyp to modify the include dir read from the pkg-config file. Also from 0.9-beta onwards the pkg-config file has changed from libnanomsg to nanomsg.

I'll probably get around to sending a PR for this but opening this issue in case anyone else can get to it before me.

Thanks.
Deepak.

**Comment by reqshark** [comment]
thanks Deepak, yea we should probably add the additional path

**Comment by antitoxic** [comment]
I tried doing: 
```
ln -s /usr/local/lib/pkgconfig/nanomsg.pc /usr/local/lib/pkgconfig/libnanomsg.pc
```

But I'm getting:

```
make: Entering directory '/projects/mobx-test/node_modules/nanomsg/build'
  CXX(target) Release/obj.target/node_nanomsg/src/node_nanomsg.o
../src/node_nanomsg.cc:5:16: fatal error: nn.h: No such file or directory
 #include <nn.h>
                ^
compilation terminated.
```

**Comment by nickdesaulniers** [comment]
`node-gyp rebuild --use_system_libnanomsg=true --verbose` might help
